### ISSUE TITLE
Falha ao extrair relatório Defeitos TV

### ISSUE THREAD

**Issue by henmerlin** [pjefika/backloglist#1]
Dia: 12/11/2016. 
Falha ao extrair relatório de Defeitos TV

**Comment by henmerlin** [comment]
#fix in commit #c9964a226a2b1ae4657dff2544b4ab26b7a93f21

**Comment by henmerlin** [comment]
This closes #1, closes #21.

**Comment by henmerlin** [comment]
Resolvido

**Comment by henmerlin** [comment]
Qual foi a tratativa realizada anteriormente?

**Comment by FabioClem** [comment]
Problema: defeito inserido na base incorretamente, não possui instancia/tipificação e nem datas somente SS, removido da base defeito nulo.
